services:
  enclosure-ui:
    environment:
      TRUENAS_API_KEY_FILE: /run/secrets/truenas_api_key
      TRUENAS_API_PASSWORD_FILE: /run/secrets/truenas_api_password
      SSH_PASSWORD_FILE: /run/secrets/ssh_password
      SSH_SUDO_PASSWORD_FILE: /run/secrets/ssh_sudo_password
      ADMIN_AUTH_PASSWORD_FILE: /run/secrets/admin_auth_password
    secrets:
      - truenas_api_key
      - truenas_api_password
      - ssh_password
      - ssh_sudo_password
      - admin_auth_password

  enclosure-admin:
    environment:
      TRUENAS_API_KEY_FILE: /run/secrets/truenas_api_key
      TRUENAS_API_PASSWORD_FILE: /run/secrets/truenas_api_password
      SSH_PASSWORD_FILE: /run/secrets/ssh_password
      SSH_SUDO_PASSWORD_FILE: /run/secrets/ssh_sudo_password
      ADMIN_AUTH_PASSWORD_FILE: /run/secrets/admin_auth_password
    secrets:
      - truenas_api_key
      - truenas_api_password
      - ssh_password
      - ssh_sudo_password
      - admin_auth_password

secrets:
  truenas_api_key:
    file: ./secrets/truenas_api_key
  truenas_api_password:
    file: ./secrets/truenas_api_password
  ssh_password:
    file: ./secrets/ssh_password
  ssh_sudo_password:
    file: ./secrets/ssh_sudo_password
  admin_auth_password:
    file: ./secrets/admin_auth_password
