"""Freeze public release DDL without importing a configured history service.

Run from the repository root. Only the named Git objects and AST declarations
are read. Generated contracts are reviewed source artifacts, not schema versions.
"""
from __future__ import annotations

import ast
import json
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[1]
REFS = ("v0.9.0", "v0.11.0", "v0.22.0", "v0.22.2")
DECLARATIONS = {
    "SCHEMA", "SLOT_STATE_OPTIONAL_COLUMNS", "SLOT_EVENT_OPTIONAL_COLUMNS",
    "METRIC_SAMPLE_OPTIONAL_COLUMNS",
}


def freeze() -> list[dict]:
    records = []
    for ref in REFS:
        commit = subprocess.check_output(
            ["git", "rev-parse", f"{ref}^{{commit}}"], cwd=ROOT, text=True,
        ).strip()
        source = subprocess.check_output(
            ["git", "show", f"{commit}:history_service/store.py"], cwd=ROOT, text=True,
        )
        tree = ast.parse(source)
        declarations = {}
        for node in tree.body:
            if isinstance(node, (ast.Assign, ast.AnnAssign)):
                target = node.targets[0] if isinstance(node, ast.Assign) else node.target
                if isinstance(target, ast.Name) and target.id in DECLARATIONS and node.value is not None:
                    declarations[target.id] = ast.literal_eval(node.value)
        indexes = []
        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef) and node.name == "_ensure_identity_indexes":
                indexes = [
                    child.value for child in ast.walk(node)
                    if isinstance(child, ast.Constant) and isinstance(child.value, str)
                    and "CREATE INDEX" in child.value
                ]
        records.append({
            "ref": ref, "commit": commit,
            "schema": declarations["SCHEMA"],
            "optional_columns": {
                table: list(declarations.get(key, {}).items())
                for table, key in (
                    ("slot_state_current", "SLOT_STATE_OPTIONAL_COLUMNS"),
                    ("slot_events", "SLOT_EVENT_OPTIONAL_COLUMNS"),
                    ("metric_samples", "METRIC_SAMPLE_OPTIONAL_COLUMNS"),
                )
            },
            "identity_indexes": indexes,
        })
    return records


if __name__ == "__main__":
    records = freeze()
    (ROOT / "history_service/schema_contracts.json").write_text(
        json.dumps(records, indent=2) + "\n", encoding="utf-8",
    )
    # Independent frozen initialized SQL for tests. Tests never import the
    # production schema declarations or regenerate predecessors at test time.
    import sqlite3
    fixtures = []
    for record in records:
        connection = sqlite3.connect(":memory:")
        connection.executescript(record["schema"])
        for table, columns in record["optional_columns"].items():
            existing = {row[1] for row in connection.execute(f"PRAGMA table_info({table})")}
            for name, definition in columns:
                if name not in existing:
                    connection.execute(f"ALTER TABLE {table} ADD COLUMN {name} {definition}")
        for sql in record["identity_indexes"]:
            connection.execute(sql)
        fixtures.append((record["ref"], record["commit"], "\n".join(connection.iterdump())))
        connection.close()
    (ROOT / "tests/history_schema_fixtures.py").write_text(
        '"""Frozen public initialized release DDL; tag and full commit per fixture.\n'
        'Generated by scripts/freeze_history_schema_contracts.py, not current SCHEMA.\n'
        'No private database input.\n"""\n\n'
        + "RELEASE_SCHEMAS = " + repr(tuple(fixtures)) + "\n", encoding="utf-8",
    )
    print("Frozen release contracts:", ", ".join(record["ref"] for record in records))
